Repository redis/rueidis, pull requests merged in 2023-05, with the labels that each got.

#217 Release drafter
  .github/release-drafter-config.yml
  .github/workflows/release-drafter.yml
Labels: maintenance

#214 feat: NewSimpleCacheAdapter converts a SimpleCache into CacheStore
  cache.go
  cache_test.go
Labels: feature

#219 feat: supports client side caching for single key scripting
  hack/cmds/gen.go
  internal/cmds/cmds.go
  internal/cmds/cmds_test.go
  internal/cmds/gen_scripting.go
  internal/cmds/gen_scripting_test.go
Labels: feature

#220 feat: supports client side caching for single key scripting in rueidiscompat
  rueidiscompat/adapter.go
  rueidiscompat/adapter_test.go
Labels: feature

#221 fix: verify commands built by MGet & MSet helpers
  internal/cmds/cmds.go
  internal/cmds/cmds_test.go
Labels: bug

#222 feat: rueidis.MDel helper
  helper.go
  helper_test.go
  internal/cmds/cmds.go
  internal/cmds/cmds_test.go
  redis_test.go
Labels: feature

#223 feat: add JSON.MERGE, JSON.MSET, GRAPH.CONSTRAINT commands
  hack/cmds/commands_graph.json
  hack/cmds/commands_json.json
  internal/cmds/gen_graph.go
  internal/cmds/gen_graph_test.go
  internal/cmds/gen_json.go
  internal/cmds/gen_json_test.go
Labels: feature

#224 feat: add rueidis.JsonMSet helper
  helper.go
  helper_test.go
  internal/cmds/cmds.go
  internal/cmds/cmds_test.go
Labels: feature

#232 fix: correct RESP3 map type generated by mock.RedisMap helper
  mock/result.go
  mock/result_test.go
Labels: bug

#230 feat: replace RedisResult.RedisError() with rueidis.IsRedisErr() to avoid confusion
  lua.go
  lua_test.go
  message.go
  message_test.go
Labels: feature, breakingchange

#228 chore: setup tests on github action
  .github/workflows/tests.yml
  dockertest.sh
  hack/cmds/gen.go
  internal/cmds/gen_bf_test.go
  internal/cmds/gen_bitmap_test.go
  internal/cmds/gen_cf_test.go
  internal/cmds/gen_cms_test.go
  internal/cmds/gen_connection_test.go
  internal/cmds/gen_gears_test.go
  internal/cmds/gen_generic_test.go
  internal/cmds/gen_geo_test.go
  internal/cmds/gen_inference_test.go
  internal/cmds/gen_json_test.go
  internal/cmds/gen_list_test.go
  internal/cmds/gen_model_test.go
  internal/cmds/gen_search_test.go
  internal/cmds/gen_server_test.go
  internal/cmds/gen_sorted_set_test.go
  internal/cmds/gen_stream_test.go
  internal/cmds/gen_string_test.go
  internal/cmds/gen_suggestion_test.go
  internal/cmds/gen_tdigest_test.go
  internal/cmds/gen_tensor_test.go
  internal/cmds/gen_timeseries_test.go
  internal/cmds/gen_topk_test.go
  rueidis_test.go
Labels: maintenance

#233 Improve leak detection
  README.md
  client_test.go
  cluster_test.go
  helper_test.go
  lru_test.go
  lua_test.go
  mux_test.go
  pipe_test.go
  pool_test.go
  pubsub_test.go
  redis_test.go
  ring_test.go
  rueidis_test.go
  sentinel_test.go
  singleflight_test.go
Labels: maintenance

#234 test: retry github action test
  .github/workflows/tests.yml
  dockertest.sh
  redis_test.go
Labels: maintenance

#235 test: use circleci
  .circleci/config.yml
  .github/workflows/tests.yml
  README.md
  dockertest.sh
  redis_test.go
  rueidis_test.go
Labels: maintenance
