Repository redis/rueidis, pull requests merged in 2023-07, with the labels that each got.

#301 fix: hanging in the cancel fn of rueidislock.TryWithContext
  rueidislock/lock.go
  rueidislock/lock_test.go
Labels: bug

#302 perf: reduce unnecessary calls to conn.SetDeadline
  pipe.go
Labels: enhancement

#303 perf: no allocations for redis OK responses
  resp.go
Labels: enhancement

#304 feat: rueidisaside
  rueidisaside/README.md
  rueidisaside/aside.go
  rueidisaside/aside_test.go
Labels: feature

#309 feat: add ClientBuilder to rueidisaside.ClientOption
  rueidisaside/aside.go
  rueidisaside/aside_test.go
Labels: feature

#310 feat: match lowercase hello command
  pipe.go
  pipe_test.go
Labels: bug

#313 feat: always using Redis 7.2 CLIENT SETINFO command to set library name
  mux_test.go
  pipe.go
  pipe_test.go
  rueidis_test.go
Labels: feature

#315 feat: export command builder type
  client.go
  cluster.go
  cmds.go
  lua_test.go
  mock/client.go
  rueidis.go
  rueidishook/hook.go
  rueidisotel/trace.go
  sentinel.go
Labels: feature

#316 feat: introduce CoreClient as a shared interface between the Client and the DedicatedClient
  rueidis.go
Labels: feature

#321 fix: handle MOVED errors for non-readonly commands in DoMulti
  cluster.go
  cluster_test.go
Labels: bug
