Repository redis/rueidis, pull requests merged in 2023-09, with the labels that each got.

#360 feat: detect misuse of client.Dedicate()
  client.go
  client_test.go
  cluster.go
  cluster_test.go
  rueidis.go
Labels: enhancement

#365 fix: enable gc to eagerly recycle used elements on ring queues
  ring.go
Labels: bug

#370 fix: allows cmds.Bitfield() to be completed by Get()
  hack/cmds/commands.json
  internal/cmds/gen_bitmap.go
  internal/cmds/gen_bitmap_test.go
Labels: bug

#376 feat: support multiple addresses #317
  README.md
  url.go
  url_test.go
Labels: feature

#378 feat: avoid using QUIT command
  internal/cmds/cmds.go
  mux_test.go
  pipe.go
  pipe_test.go
  ring_test.go
  rueidis_test.go
Labels: enhancement
