Repository redis/rueidis, pull requests merged in 2023-06, with the labels that each got.

#274 perf: use runtime.GOMAXPROCS() to determine max concurrency
  internal/util/parallel.go
Labels: enhancement

#276 fix: Use net.JoinHostPort to join ip to handle IPv6
  sentinel.go
Labels: bug

#280 perf: boost DoMulti/Cache of the cluster by grouping cmds to conns, not slots
  cluster.go
  cluster_test.go
  pipe.go
  pipe_test.go
Labels: enhancement

#281 perf: speed up MGet/Cache/MSet heplers by grouping commands by connections instead of slots
  helper.go
  helper_test.go
Labels: enhancement

#285 fix: cluster of 1 node with unknown ip
  cluster.go
  cluster_test.go
Labels: bug, enhancement

#286 perf: reduce contention caused by the usage of runtime.GOMAXPROCS
  internal/util/parallel.go
  internal/util/parallel_test.go
  lua.go
  mux.go
  rueidiscompat/adapter.go
Labels: enhancement

#287 perf: reuse intermediate alloc
  client.go
  client_test.go
  cluster.go
  cluster_test.go
  helper.go
  helper_test.go
  internal/util/pool.go
  internal/util/pool_test.go
  mux.go
  mux_test.go
  pipe.go
  pipe_test.go
  sentinel.go
  sentinel_test.go
Labels: enhancement
