Repository redis/rueidis, pull requests merged in 2023-12, with the labels that each got.

#415 feat: allow setting expiry on om entities by adding an exat field
  om/README.md
  om/conv.go
  om/hash.go
  om/hash_test.go
  om/json.go
  om/json_test.go
  om/schema.go
  om/schema_test.go
Labels: feature

#420 fix: correct CLIENT SETINFO connection setup
  mux_test.go
  pipe.go
  pipe_test.go
  rueidis.go
  rueidis_test.go
Labels: bug

#425 fix: rueidis.ParseURL() cannot parse unix address
  url.go
  url_test.go
Labels: bug

#421 feat: add built-in metrics
  go.mod
  go.sum
  rueidisotel/metrics.go
  rueidisotel/metrics_test.go
  rueidisotel/trace.go
Labels: feature

#427 fix: random nil dereference caused by non-zero PipelineMultiplex
  mux.go
  redis_test.go
Labels: bug

#428 OTEL tweaks
  rueidisotel/metrics.go
  rueidisotel/trace.go
Labels: maintenance

#433 fix: rueidiscompat's ZPopMax and ZPopMin with count 1
  rueidiscompat/adapter.go
Labels: bug

#430 fix: send readonly command
  cluster.go
  cluster_test.go
Labels: enhancement
