Repository redis/rueidis, pull requests merged in 2024-01, with the labels that each got.

#441 feat: SetSlot to override the calculated key slot of a command
  internal/cmds/cmds.go
  internal/cmds/cmds_test.go
Labels: feature

#443 doc: Modify rueidisotel documentation
  rueidisotel/README.md
Labels: documentation

#446 fix wrong block tag setting
  hack/cmds/gen.go
  internal/cmds/gen_stream.go
  internal/cmds/gen_timeseries.go
Labels: bug

#458 fix: rueidislock deadlock caused by the absence of peers
  rueidislock/lock.go
  rueidislock/lock_test.go
Labels: bug

#459 Feat: Align `go-redis` `JSONCmdable`
  rueidiscompat/adapter.go
  rueidiscompat/adapter_test.go
  rueidiscompat/command.go
Labels: feature
